Repository kubesphere/community, pull requests merged in 2020-10, with the labels that each got.

#177 add custom monitoring enhancement proposal
  sig-observability/concepts-and-designs/202009_custom-monitoring-enhancement.md
Labels: approved, dco-signoff: yes, size/L

#178 Add KubeEdge integration proposal
  sig-edge/concepts-and-designs/kubesphere-kubeedge-integration.md
  sig-edge/images/edge-router.png
  sig-edge/images/log.png
Labels: dco-signoff: yes, size/L

#180 Add ZH-CN task list
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/M

#181 claim translation task
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#182 Update task assignment guide name
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#183 Add translator for quickstarts
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#186 Add en doc list
  sig-docs/english-doc-list/KubeSphere 3.0 Documentation List.md
Labels: dco-signoff: yes, size/M

#187 Update doc list name
  sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
Labels: dco-signoff: yes, size/XS

#185 Update ZH-CN Localization Task.md
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: no, size/XS

#188 update doc list
  sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
Labels: dco-signoff: yes

#189 Update KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
  sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
Labels: dco-signoff: no, size/S

#184 Update ZH-CN task list
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#195 refine sigs-writing-plans.md
  sigs-writing-plans.md
Labels: dco-signoff: yes, size/XS

#200 doc(l10n-task): claim translation owner
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/S

#197 Update ZH-CN Localization Task.md
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: no, size/M

#202 claim the tasks
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#192 Update KubeSphere 3.0 Documentation List (Built-in Apps)
  sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
Labels: dco-signoff: yes, size/XS

#203 get the task
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#205 assign apps docs
  sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
Labels: dco-signoff: yes, size/XS

#208 update custom alerting design
  sig-observability/concepts-and-designs/custom alerting.md
Labels: dco-signoff: yes, size/L

#207 Update ZH-CN task list
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/S

#212 PR NUM.
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#211 PR NUM.
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#191 add the writer info of deploy harbor
  sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
Labels: approved, dco-signoff: no, lgtm, size/XS

#204 claim devops documentation
  sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
Labels: approved, dco-signoff: yes, lgtm, size/S
