Repository kubesphere/community, pull requests merged in 2020-04, with the labels that each got.

#51 Update OWNERS
  OWNERS
Labels: lgtm, size/XS

#21 devops event docs
  developer-guide/concepts-and-designs/sig-devops/devops-event.md
  developer-guide/concepts-and-designs/sig-devops/images/devops-event.svg
Labels: lgtm

#11 update devops observability
  STEERING COMMITTEE.md
  developer-guide/concepts-and-designs/sig-devops/devops_observability.md
Labels: lgtm

#15 devops crd docs
  developer-guide/concepts-and-designs/sig-devops/devops-crd.md
Labels: lgtm

#16 update s2i trigger design
  developer-guide/concepts-and-designs/sig-devops/images/s2i-trigger-flow.svg
  developer-guide/concepts-and-designs/sig-devops/images/s2i_arch.png
  developer-guide/concepts-and-designs/sig-devops/s2i_trigger.md
  sig-devops/concepts-and-designs/s2i-b2i-overview.md
Labels: lgtm

#56 Add OWNERS in sig cloud providers and sig storage
  sig-cloud-providers/OWNERS
  sig-storage/OWNERS
Labels: approved, lgtm, size/S

#49 Storage capability interface
  sig-storage/concepts-and-designs/image/storage-capability.jpg
  sig-storage/concepts-and-designs/storage-capability-interface.md
Labels: approved, lgtm, size/S

#41 Add csi plugin docs
  sig-storage/concepts-and-designs/csi-plugin.md
  sig-storage/concepts-and-designs/image/csi-plugin.jpg
Labels: approved, lgtm, size/S

#55 research plan about CSI of AWS
  sig-cloud-providers/aws/csi.md
Labels: approved, lgtm, size/S

#54 Add projects to SIG Observability
  sig-observability/README.md
Labels: approved, lgtm, size/S

#60 Update sig-apps members
  sig-apps/OWNERS
  sig-apps/README.md
Labels: approved, lgtm, size/S
