Repository kubesphere/community, pull requests merged in 2020-08, with the labels that each got.

#119 add community-collaboration-for-v3.0.0.md
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: approved, dco-signoff: yes, size/M

#120 add huaweicloud to community-collaboration-for-v3.0.0.md
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes

#124 update
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#123 assign Azure AKS task
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#125 add Howie66 as an assignee into this task
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#127 add LiuG-lynx as an assignee into this task
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#131 get aws eks task
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#132 refine community-collaboration-for-v3.0.0.md
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: approved, dco-signoff: yes, size/XS

#133 docs(installation): add huawei cce and assignee
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#136 Digital Ocean reservation by GekoCloud
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#137 add kubesphere weekly
  kubesphere-weekly.md
Labels: dco-signoff: yes, size/S

#139 update pr url for task
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#143 get task
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#148 update pr url for task
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#146 claim task #4
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#149 Claim ks on gke installation guide
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes

#152 update installation community-collaboration
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#157 Update PR link
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#159 Fix typo
  sig-release/releases/release-v300.md
Labels: approved, dco-signoff: no, lgtm, size/XS

#160 adopt the task of KubeSphere on Tencent TKE
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#162 add LiuG-lynx as an assignee into task 8
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#163 Adjust metrics server switch desc
  sig-release/releases/release-v300.md
Labels: dco-signoff: yes, size/XS
