Repository kubesphere/community, pull requests merged in 2020-12, with the labels that each got.

#270 调整 DevOps 工作坊有关奖励部分的描述
  sig-devops/events/2020-12-19-workshop-beijing.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#269 Add PR links
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#273 task claim on Index Page under App Store-Felixnoo
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/S

#271 Update zhcn list
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/S

#274 task-claim-Felixnoo
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/S

#272 Add some articles！
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#155 add KubeSphere-terraform.md
  sig-installation/guideline/KubeSphere-terraform-zh.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#277 Update sig info
  sig-storage/OWNERS
  sig-storage/README.md
  sig-virtualization/README.md
  sigs.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#278 Update owners
  sig-devops/OWNERS
  sig-docs/OWNERS
  sig-docs/README.md
  sig-edge/OWNERS
  sig-edge/README.md
  sig-microservice/OWNERS
  sig-microservice/README.md
  sig-multicluster/OWNERS
  sig-multicluster/README.md
  sig-multitenancy/OWNERS
  sig-network/OWNERS
  sig-observability/OWNERS
  sigs.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#276 Add PR links.
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#275 task claim
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#281 Add PR link.
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, size/XS

#282 Get some tasks.
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/M
