Repository kubesphere/community, pull requests merged in 2020-06, with the labels that each got.

#95 add KubeSphere multicluster setup documents, chinese version
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README_zh.md
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/agent.png
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/clusters.png
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/direct_import.png
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/proxy.png
Labels: approved, lgtm, size/L

#97 Update adding cluster guide
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README_zh.md
Labels: approved, size/XS

#99 add en readme
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README.md
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/agent-en.png
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/import.png
Labels: approved, lgtm, size/L

#98 Update adding multi cluster doc
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README_zh.md
Labels: approved, lgtm, size/XS

#101 Add console localization guide
  sig-docs/README.md
  sig-docs/localization/how-to-localize-console.md
Labels: approved, lgtm, size/M

#103 Add explanations for copying zh folder for loc guide
  sig-docs/localization/how-to-localize-console.md
Labels: approved, lgtm, size/XS
