Repository kubesphere/community, pull requests merged in 2020-07, with the labels that each got.

#104 add image mg guide
  sig-docs/image-management/image-management.md
Labels: approved, lgtm, size/M

#105 Update target branch for pr submission
  sig-docs/localization/how-to-localize-console.md
Labels: approved, lgtm, size/XS

#106 update multi cluster setup documentation
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README.md
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README_zh.md
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/direct_import.png
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/direct_import_en.png
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/import.png
Labels: approved, lgtm, size/L

#107 Fix wrong param name
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README.md
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README_zh.md
Labels: approved, lgtm, size/XS

#111 Add desc for console language option
  sig-docs/localization/how-to-localize-console.md
Labels: approved, lgtm, size/M

#110 modify sig-network docs
  sig-network/concepts-and-designs/kubesphere-network-policy.md
Labels: approved, lgtm, size/XS

#112 update doc about kubesphere network policy
  sig-network/concepts-and-designs/kubesphere-network-policy.md
Labels: size/M

#115 add set member cluster jwtSecret documentation
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README_zh.md
Labels: approved, size/S

#114 Update loc guide
  sig-docs/localization/how-to-localize-console.md
Labels: approved, lgtm, size/S

#113 add kubekey upgrade design
  OWNERS
  sig-installation/kubekey/upgrade.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#116 Update set up multicluster guide
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README.md
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README_zh.md
Labels: approved, dco-signoff: no, size/M

#117 add release notes for 3.0.0 (initial version)
  sig-release/releases/release-v300.md
Labels: approved, dco-signoff: yes, lgtm, size/S
