Repository kubesphere/community, pull requests merged in 2020-05, with the labels that each got.

#61 fix:typo and error link
  developer-guide/development/development-workflow.md
  developer-guide/development/how-to-run-kubesphere-core.md
Labels: approved, lgtm, size/XS

#30 audit log filter design draft
  sig-multitenancy/concepts-and-designs/requestcontext.md
  sig-multitenancy/draft/audit-logging.md
Labels: approved, lgtm

#59 add developer doc about kubesphere network policy
  sig-network/concepts-and-designs/kubesphere-network-policy.md
Labels: approved, lgtm, size/M

#63 Add sig edge
  sig-edge/OWNERS
  sig-edge/README.md
Labels: size/S

#65 Update documents and OWNER
  sig-multicluster/OWNERS
  sig-multicluster/README.md
  sig-multicluster/concepts-and-designs/architecture.md
  sigs.md
Labels: approved, size/S

#69 how teleprensence works
  developer-guide/development/how-telepresence-works.md
  images/telepresence-toplogy.png
Labels: approved, lgtm, size/S

#72 fix error img path
  sig-devops/concepts-and-designs/devops-pipeline-overview.md
  sig-devops/concepts-and-designs/s2i-b2i-overview.md
  sig-devops/images/devops-api.png
  sig-devops/images/s2i-arch.png
  sig-devops/images/s2i-workflow.png
Labels: approved, lgtm, size/XS

#73 Update owners and readme
  sig-console/OWNERS
  sig-console/README.md
  sig-docs/OWNERS
  sig-docs/README.md
Labels: approved, size/S

#75 Update docs
  sig-observability/OWNERS
  sig-observability/README.md
  sig-observability/concepts-and-designs/kubesphere-logging.md
  sig-observability/concepts-and-designs/kubesphere-monitoring.md
  sig-observability/development/kubesphere-logging-development-guide.md
  sig-observability/development/kubesphere-monitoring-development-guide.md
  sig-observability/images/kubesphere-logging-fluentbit.png
  sig-observability/images/kubesphere-logging-overview.png
  sig-observability/images/kubesphere-monitoring-architecture.png
Labels: approved, size/M

#78 20200507
  sig-release/meeting-notes/weekly-status/20200507.md
Labels: size/M

#79 debug with telepresence
  developer-guide/development/how-telepresence-works.md
  developer-guide/development/how-to-connect-remote-service.md
Labels: approved, lgtm, size/S

#82 Add other storage system
  sig-storage/concepts-and-designs/csi-plugin.md
Labels: approved, lgtm, size/XS

#84 20200514
  sig-release/meeting-notes/weekly-status/20200514.md
Labels: size/M

#88 Improve the telepresence guide
  developer-guide/development/how-telepresence-works.md
  images/telepresence-topology.png
Labels: approved, lgtm, size/S

#90 fix document url
  sig-devops/README.md
Labels: approved, lgtm, size/XS
