Repository kubesphere/community, pull requests merged in 2020-09, with the labels that each got.

#164 Digital Ocean reservation by GekoCloud: Set link to PR
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#167 claim
  sig-docs/installation/community-collaboration-for-v3.0.0.md
Labels: dco-signoff: yes, size/XS

#169 update fluent bit operator arch image
  developer-guide/concepts-and-designs/README.md
  sig-observability/README.md
  sig-observability/concepts-and-designs/kubesphere-logging-v2.1.1.md
  sig-observability/concepts-and-designs/kubesphere-logging-v3.0.0.md
  sig-observability/images/kubesphere-logging-fluentbit-v2.1.1.png
  sig-observability/images/kubesphere-logging-fluentbit-v3.0.0.svg
Labels: dco-signoff: yes, size/M

#171 Update multicluster clusterconfiguration command
  sig-multicluster/how-to-setup-multicluster-on-kubesphere/README.md
Labels: dco-signoff: yes, size/XS

#174 add notification manager design for kubesphere v3.1.0
  sig-observability/concepts-and-designs/multi-tenant notification.md
Labels: dco-signoff: yes, size/XL

#175 add custom alerting design for kubesphere v3.1.0
  sig-observability/concepts-and-designs/custom alerting.md
Labels: dco-signoff: yes, size/L

#176 adjust document format
  sig-observability/concepts-and-designs/multi-tenant notification.md
Labels: dco-signoff: yes, size/S
