Repository kubesphere/community, pull requests merged in 2020-11, with the labels that each got.

#215 Claim 'Multi-cluster Management' zh-cn localization
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#179 Add workspace group design
  sig-multitenancy/concepts-and-designs/user-group-authorization.png
  sig-multitenancy/concepts-and-designs/user-group-designs.md
  sig-multitenancy/concepts-and-designs/user-group-designs.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#216 add installing-on-linux_index_zh
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm

#219 eidt Task list
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: no, lgtm, size/XS

#94 Add myself as a member of DevOps SIG
  sig-devops/README.md
Labels: approved, lgtm, size/XS

#220 update logging & monitoring dev guide v3.0.0
  sig-observability/README.md
  sig-observability/development/kubesphere-logging-development-guide-v2.1.1.md
  sig-observability/development/kubesphere-logging-development-guide-v3.0.0.md
  sig-observability/development/kubesphere-monitoring-development-guide-v2.1.1.md
  sig-observability/development/kubesphere-monitoring-development-guide-v3.0.0.md
Labels: dco-signoff: yes, size/L

#222 fix typo
  sig-observability/concepts-and-designs/202009_custom-monitoring-enhancement.md
Labels: dco-signoff: yes, size/XS

#224 chore: Update README.md
  sig-devops/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#227 get the task
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/M

#225 update PR Link
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, lgtm, size/XS

#229 update PR Link 464
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#232 Update kubesphere-kubeedge-integration document
  sig-edge/concepts-and-designs/kubesphere-kubeedge-integration.md
  sig-edge/images/edge-router.png
  sig-edge/images/edge-watcher.png
  sig-edge/images/edge_join_1.png
  sig-edge/images/edge_join_2.png
Labels: dco-signoff: yes, size/M

#209 update proposal of notification-manager for kubesphere 3.1
  sig-observability/concepts-and-designs/multi-tenant notification.md
  sig-observability/images/global-receiver-config.png
  sig-observability/images/tenant-receiver-config.png
Labels: dco-signoff: yes, size/S

#239 update pr link for ZH-CN_Localization_Task.md
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#237 get new translate tasks
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#236 add all-in-one on linux zh docs
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#235 Take the second task.
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#231 add doc about ippool
  sig-network/concepts-and-designs/ippool.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#230 update development-guide
  developer-guide/development/README.md
  developer-guide/development/development-workflow.md
  developer-guide/development/how-to-connect-remote-service.md
  developer-guide/development/how-to-run-kubesphere-core.md
  developer-guide/development/pull-requests.md
  developer-guide/development/quickstart.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#240 update sig virtualization README
  sig-virtualization/README.md
Labels: approved, dco-signoff: yes, size/S

#243 update sig-virtualization
  sig-virtualization/OWNERS
  sig-virtualization/README.md
  sig-virtualization/concepts-and-designs/kubesphere-kubevirt-integration.md
  sig-virtualization/images/diskvolume.png
  sig-virtualization/images/imagetemplate.png
  sig-virtualization/images/virtualmachine.png
Labels: dco-signoff: yes, size/L

#241 Update README.md
  sig-network/README.md
Labels: approved, dco-signoff: yes, size/XS

#244 update proposal and change the api group
  sig-observability/concepts-and-designs/multi-tenant notification.md
Labels: dco-signoff: yes, size/L

#245 Signed-off-by: willzhang willzhmic@outlook.com
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#251 领取jobs任务
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/M

#255 translate k8s
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#253 get translator task
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#252 Add PR link Signed-off-by: kaige <154599029@qq.com>
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/S

#257 Add meeting calendar for observability and edge
  sig-edge/README.md
  sig-observability/README.md
Labels: approved, dco-signoff: yes, size/S

#256 Update ZH-CN guide list
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/S

#258 Add PR link
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#260 Get more task about DevOps and add some PR links.
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#262 translate linux overview
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#261 Add a PR link
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#264 Add PR link
  sig-docs/localization/ZH-CN Localization Task.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#265 Add task translate article in 'DevOps User Guide'
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, lgtm, size/XS

#263 翻译 Job
  sig-docs/.DS_Store
  sig-docs/localization/ZH-CN Localization Task.md
Labels: dco-signoff: yes, size/XS

#266 Add a workshop event in Beijing
  sig-devops/README.md
  sig-devops/events/2020-12-19-workshop-beijing.md
Labels: dco-signoff: yes, size/M

#268 Update kubeedge keadm images
  sig-edge/images/edge_join_1.png
  sig-edge/images/edge_join_2.png
Labels: approved, dco-signoff: no, size/XS
