Repository kubesphere/community, pull requests merged in 2021-02, with the labels that each got.

#297 Modify the code format: adjust the symbol at the beginning of the line
  developer-guide/development/development-workflow.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#302 Add SIG Advocacy and Outreach with the permit of TOC
  sig-advocacy-and-outreach/OWNERS
  sig-advocacy-and-outreach/README.md
  sig-advocacy-and-outreach/gsoc/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#303 Submit project proposals list for GSoC 2021
  sig-advocacy-and-outreach/gsoc/README.md
  sig-advocacy-and-outreach/gsoc/customize-receiving-users-via-webhook.md
  sig-advocacy-and-outreach/gsoc/exposure-of-loadBalancer-service-using-iptables-nat-rules.md
  sig-advocacy-and-outreach/gsoc/kubeSphere-jenkins-client-refactor.md
  sig-advocacy-and-outreach/gsoc/kubeSphere-tekton-integration.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#305 Reviewed customize-notification-receivers-via-webhook-en.
  sig-advocacy-and-outreach/gsoc/README.md
  sig-advocacy-and-outreach/gsoc/customize-notification-receivers-using-a-webhook.md
  sig-advocacy-and-outreach/gsoc/customize-receiving-users-via-webhook.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#304 Jenkins Client Refactor & Tekton Integration refined.
  sig-advocacy-and-outreach/gsoc/kubeSphere-jenkins-client-refactor.md
  sig-advocacy-and-outreach/gsoc/kubeSphere-tekton-integration.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#307 Reviewed expose-loadbalancer-services-using-iptables-nat-rules-en.
  sig-advocacy-and-outreach/gsoc/README.md
  sig-advocacy-and-outreach/gsoc/expose-loadbalancer-services-using-iptables-nat-rules.md
  sig-advocacy-and-outreach/gsoc/exposure-of-loadBalancer-service-using-iptables-nat-rules.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#309 Add SIG advocacy and outreach into the summary page
  sigs.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#290 Add artwork of all SIG cover images
  images/artwork/SIG-AppStore.png
  images/artwork/SIG-DevOps.png
  images/artwork/SIG-Docs.png
  images/artwork/SIG-Edge.png
  images/artwork/SIG-Installation.png
  images/artwork/SIG-Multicluster.png
  images/artwork/SIG-Multitenancy.png
  images/artwork/SIG-Network.png
  images/artwork/SIG-Observability.png
  images/artwork/SIG-Virtualization.png
Labels: approved, dco-signoff: yes, lgtm, size/XS

#311 Add mailing list for SIG DevOps, SIG Advocacy and Outreach
  sig-advocacy-and-outreach/README.md
  sig-devops/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#310 Add a link in the sig advocacy to gsoc
  sig-advocacy-and-outreach/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#308 Add GSoC student application process document
  sig-advocacy-and-outreach/gsoc/README.md
  sig-advocacy-and-outreach/gsoc/students-application-process.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#286 Remove directory .DS_Store which is useless
  .gitignore
  images/.DS_Store
  sig-docs/.DS_Store
Labels: dco-signoff: yes, lgtm, size/XS
