Repository kubesphere/community, pull requests merged in 2021-05, with the labels that each got.

#328 improvement: tekton summer ospp
  sig-advocacy-and-outreach/summer-ospp/kubeSphere-tekton-integration.md
  sig-advocacy-and-outreach/summer-ospp/kubeSphere-tekton-integration_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#331 update summer 2021's proposals
  sig-advocacy-and-outreach/summer-ospp/README.md
  sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md
  sig-advocacy-and-outreach/summer-ospp/TODO-LIST.md
  sig-advocacy-and-outreach/summer-ospp/customize-notification-receivers-using-a-webhook.md
  sig-advocacy-and-outreach/summer-ospp/customize-notification-receivers-using-a-webhook_zh-CN.md
  sig-advocacy-and-outreach/summer-ospp/support-send-notifications-to-pushover_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#330 Add gatekeeper inegration project proposal
  sig-advocacy-and-outreach/summer-ospp/README.md
  sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md
  sig-advocacy-and-outreach/summer-ospp/kubesphere-gatekeeper-integration.md
  sig-advocacy-and-outreach/summer-ospp/kubesphere-gatekeeper-integration_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#332 Update the chinese version of porterlb summer-ospp
  sig-advocacy-and-outreach/summer-ospp/README.md
  sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md
  sig-advocacy-and-outreach/summer-ospp/expose-loadbalancer-services-using-iptables-nat-rules.md
  sig-advocacy-and-outreach/summer-ospp/expose-loadbalancer-services-using-iptables-nat-rules_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#333 Update mentor in Summer OSPP
  sig-advocacy-and-outreach/summer-ospp/README.md
  sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md
  sig-advocacy-and-outreach/summer-ospp/expose-loadbalancer-services-using-iptables-nat-rules.md
  sig-advocacy-and-outreach/summer-ospp/expose-loadbalancer-services-using-iptables-nat-rules_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#334 Add SAML authentication inegration proposal
  sig-advocacy-and-outreach/summer-ospp/KubeSphere-SAML-integrations.md
  sig-advocacy-and-outreach/summer-ospp/KubeSphere-SAML-integrations_zh-CN.md
  sig-advocacy-and-outreach/summer-ospp/README.md
  sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#337 Add JohnNiang into devops approver and reviewer list
  sig-devops/OWNERS
  sig-devops/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#339 Add meeting video records link of devops sig
  sig-devops/OWNERS
  sig-devops/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#340 update summer ospp's proposals
  sig-advocacy-and-outreach/summer-ospp/OpenFunction-function-framework-nodejs.md
  sig-advocacy-and-outreach/summer-ospp/README.md
  sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md
  sig-advocacy-and-outreach/summer-ospp/document-localization_zh-CN.md
  sig-advocacy-and-outreach/summer-ospp/kubesphere-website_zh-CN.md
  sig-advocacy-and-outreach/summer-ospp/openfunction-website_zh-CN.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#341 Fix the wrong link of kubesphere-gatekeeper-integration
  sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md
Labels: approved, dco-signoff: no, lgtm, size/XS

#342 Add the latest images for edge-watcher
  sig-edge/images/edge-watcher.png
  sig-edge/images/edge-watcher.svg
Labels: approved, dco-signoff: yes, size/XS
