Repository kubesphere/community, pull requests merged in 2021-06, with the labels that each got.

#284 add standalone-ks proposal
  sig-multicluster/proposal/images/standalone-ks.png
  sig-multicluster/proposal/standalone-ks.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#345 Add cherry pick guide
  developer-guide/development/README.md
  developer-guide/development/cherry-picks.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#346 Add code review guide doc, pr author guide and coding conventions
  developer-guide/development/code-review-guide.md
  developer-guide/development/coding-conventions.md
  developer-guide/development/the-pr-author-guide-to-getting-through-code-review.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#350 Add docs for sig-serverless
  sig-serverless/OWNERS
  sig-serverless/README.md
Labels: dco-signoff: yes, size/M
