Repository kubesphere/community, pull requests merged in 2021-04, with the labels that each got.

#320 Submit project proposals list for Summer 2021 of Open Source Promotion Plan
  .gitignore
  sig-advocacy-and-outreach/summer-ospp/README.md
  sig-advocacy-and-outreach/summer-ospp/customize-notification-receivers-using-a-webhook.md
  sig-advocacy-and-outreach/summer-ospp/expose-loadbalancer-services-using-iptables-nat-rules.md
  sig-advocacy-and-outreach/summer-ospp/kubeSphere-jenkins-client-refactor.md
  sig-advocacy-and-outreach/summer-ospp/kubeSphere-tekton-integration.md
  sig-advocacy-and-outreach/summer-ospp/students-application-process.md
Labels: dco-signoff: yes, lgtm, size/L

#321 Update README.md in summer-ospp
  sig-advocacy-and-outreach/summer-ospp/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#323 Fix the broken link of kubekey
  sig-installation/README.md
Labels: dco-signoff: yes, size/XS

#324 Add more details of sig advocacy and outreach
  sig-advocacy-and-outreach/README.md
  sig-advocacy-and-outreach/gsoc/README.md
  sig-advocacy-and-outreach/summer-ospp/OWNERS
  sig-advocacy-and-outreach/summer-ospp/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M
