Repository kubesphere/community, pull requests merged in 2022-04, with the labels that each got.

#395 Update member list for arch sig
  sig-architecture/OWNERS
  sig-architecture/README.md
Labels: lgtm, approved, size/S

#373 Add KubeSphere Gateway Operator design doc
  sig-microservice/concepts-and-designs/KubeSphere-gateway-operator-design.md
Labels: size/L

#397 add ospp 2022
  sig-advocacy-and-outreach/ospp-2022/README.md
  sig-advocacy-and-outreach/ospp-2022/README_zh-CN.md
Labels: lgtm, size/M, approved

#401 Request to add faweizhao26 and yangchuansheng as the owner
  sig-advocacy-and-outreach/OWNERS
Labels: lgtm, approved, size/S

#396 docs(ospp): add one openfunction topic for 2022
  sig-advocacy-and-outreach/ospp-2022/openfunction-nodejs-function-framework-upgrade_zh-CN.md
Labels: lgtm, size/M, approved, kind/proposal

#404 Openfunction dapr elastic app runtime for ospp 2022
  sig-advocacy-and-outreach/ospp-2022/openfunction-dapr-elastic-app-runtime.md
Labels: lgtm, size/M, approved

#405 Add KubeEye Console2.0 project proposal for ospp2022
  sig-advocacy-and-outreach/ospp-2022/kubeeye-console2.0.md
Labels: lgtm, size/M, approved

#399 Add kubesphere sharing secret plugin project proposal
  sig-advocacy-and-outreach/ospp-2022/README_zh-CN.md
  sig-advocacy-and-outreach/ospp-2022/kubesphere-sharing-secret-plugin_zh-CN.md
Labels: lgtm, size/M, approved, kind/proposal

#403 add kubekey phase run
  sig-advocacy-and-outreach/ospp-2022/README_zh-CN.md
  sig-advocacy-and-outreach/ospp-2022/kubekey-phase-run_zh-CN.md
Labels: lgtm, size/M, approved

#398 Proposal for ks-devops && fluxcd integrations for ospp 2022
  sig-advocacy-and-outreach/ospp-2022/ks-devops-fluxcd-integrations.md
Labels: lgtm, size/M, approved, kind/proposal
