Repository kubesphere/community, pull requests merged in 2023-08, with the labels that each got.

#443 Update README.md
  ksap-ambassadorship-program/README.md
Labels: lgtm, size/XS, approved

#444 Update README.md of community
  README.md
Labels: lgtm, size/XS

#446 add new issue template
  .github/ISSUE_TEMPLATE/user_group_guest.yml
Labels: lgtm, size/M
